# Generated by Django 3.2.8 on 2021-11-22 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211112_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_electric', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='電力費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_gas', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='ガス費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Solvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_solvent', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='溶剤費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_steam', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='蒸気費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_total', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='合計費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
                ('Cost_electric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_electric')),
                ('Cost_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_gas')),
                ('Cost_solvent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_solvent')),
                ('Cost_steam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_steam')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost_water', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='水費用')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(blank=True, max_length=20, verbose_name='企業名')),
                ('Customer_tel_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Tel Number must be entered in the format: '09012345678'. Up to 15 digits allowed.", regex='^[0-9]+$')], verbose_name='電話番号')),
                ('Customer_pastal_code', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="Postal Code must be entered in the format: '1234567'. Up to 7 digits allowed.", regex='^[0-9]+$')], verbose_name='郵便番号')),
                ('Customer_address1', models.CharField(blank=True, max_length=40, null=True, verbose_name='都道府県')),
                ('Customer_address2', models.CharField(blank=True, max_length=40, null=True, verbose_name='市町村番地')),
                ('Customer_address3', models.CharField(blank=True, max_length=40, null=True, verbose_name='建物名')),
                ('Customer_input_date', models.DateField(verbose_name='登録日')),
                ('Customer_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_machine_unit_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機')),
                ('Customer_machine_inst_date', models.DateField(blank=True, null=True, verbose_name='納入日')),
                ('Customer_machine_input_date', models.DateField(verbose_name='登録日')),
                ('Customer_machine_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Machine_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_recipe_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No')),
                ('Customer_recipe_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='品種名')),
                ('Customer_recipe_time', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='運転時間')),
                ('Customer_recipe_time1', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='乾燥時間1')),
                ('Customer_recipe_time2', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='乾燥時間2')),
                ('Customer_recipe_time3', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='乾燥時間3')),
                ('Customer_recipe_time4', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='乾燥時間4')),
                ('Customer_recipe_temp1', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='温度設定1')),
                ('Customer_recipe_temp2', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='温度設定2')),
                ('Customer_recipe_temp3', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='温度設定3')),
                ('Customer_recipe_temp4', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='温度設定4')),
                ('Customer_recipe_conf1', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定1')),
                ('Customer_recipe_conf2', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定2')),
                ('Customer_recipe_conf3', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定3')),
                ('Customer_recipe_conf4', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定4')),
                ('Customer_recipe_conf5', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定5')),
                ('Customer_recipe_conf6', models.CharField(blank=True, max_length=20, null=True, verbose_name='設定6')),
                ('Customer_machine_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Customer_machine_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
                ('Customer_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_category', models.CharField(max_length=10, verbose_name='装置カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Drive_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine_drying_time', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間')),
                ('Machine_drive_count', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数')),
                ('Machine_water_used', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='水使用量')),
                ('Machine_steam_used', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='蒸気使用量')),
                ('Machine_electric_used', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='電力使用量')),
                ('Machine_gas_used', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='ガス使用量')),
                ('Data_date_year', models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年')),
                ('Data_date_month', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('Data_date_day', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('Data_datetime', models.DateTimeField(blank=True, null=True, verbose_name='データ取得日')),
                ('Machine_history_input_date', models.DateField(blank=True, verbose_name='登録日')),
                ('Machine_history_memo', models.TextField(blank=True, max_length=50, verbose_name='メモ')),
                ('Customer_machine_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine_recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Machine_model', models.CharField(max_length=20, verbose_name='型式')),
                ('Machine_model_input_date', models.DateField(verbose_name='登録日')),
                ('Machine_model_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Machine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.equipment_category')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solvent_unit_price', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='単価')),
                ('Solvent_input_date', models.DateField(verbose_name='登録日')),
                ('Solvent_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent_Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solvent_manu', models.CharField(max_length=20, verbose_name='メーカー')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solvent_name', models.CharField(max_length=20, verbose_name='溶剤名')),
            ],
        ),
        migrations.CreateModel(
            name='Trouble_Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trouble_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='異常No')),
                ('Trouble_contents', models.CharField(max_length=20, verbose_name='異常')),
                ('Trouble_input_date', models.DateField(verbose_name='登録日')),
                ('Trouble_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_model')),
            ],
        ),
        migrations.CreateModel(
            name='Trouble_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trouble_occurrence_time', models.DateTimeField(blank=True, null=True, verbose_name='発生時刻')),
                ('Trouble_recovery_time', models.DateTimeField(blank=True, null=True, verbose_name='復帰時刻')),
                ('Customer_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine')),
                ('Trouble_contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trouble_contents')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Price_Electric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_electric', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='単価')),
                ('Unit_price_electric_input_date', models.DateField(verbose_name='登録日')),
                ('Unit_price_electric_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Price_Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_gas', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='単価')),
                ('Unit_price_gas_input_date', models.DateField(verbose_name='登録日')),
                ('Unit_price_gas_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Price_Steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_steam', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='単価')),
                ('Unit_price_steam_input_date', models.DateField(verbose_name='登録日')),
                ('Unit_price_steam_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Price_Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_water', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='単価')),
                ('Unit_price_water_input_date', models.DateField(verbose_name='登録日')),
                ('Unit_price_water_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.DeleteModel(
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='machine_drive_data',
            name='machine_setting',
        ),
        migrations.RemoveField(
            model_name='machine_setting',
            name='machine_data',
        ),
        migrations.DeleteModel(
            name='Machine_data',
        ),
        migrations.DeleteModel(
            name='Machine_drive_data',
        ),
        migrations.DeleteModel(
            name='Machine_setting',
        ),
        migrations.AddField(
            model_name='solvent_manufacturer',
            name='Solvent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_name'),
        ),
        migrations.AddField(
            model_name='solvent_conf',
            name='Solvent_manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_manufacturer'),
        ),
        migrations.AddField(
            model_name='customer_machine',
            name='Machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_model'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Unit_price_water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_water'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Cost_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_water'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Machine_drive_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Unit_price_steam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_steam'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Solvent_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_conf'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Unit_price_gas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_gas'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Unit_price_electric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_electric'),
        ),
    ]
