# Generated by Django 3.2.8 on 2021-11-30 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211126_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_electric',
            name='Cost_electric',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力費用'),
        ),
        migrations.AlterField(
            model_name='cost_electric',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_electric',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='cost_gas',
            name='Cost_gas',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス費用'),
        ),
        migrations.AlterField(
            model_name='cost_gas',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_gas',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='cost_solvent',
            name='Cost_solvent',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用'),
        ),
        migrations.AlterField(
            model_name='cost_solvent',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_solvent',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='cost_steam',
            name='Cost_steam',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気費用'),
        ),
        migrations.AlterField(
            model_name='cost_steam',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_steam',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_total',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='cost_water',
            name='Cost_water',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水費用'),
        ),
        migrations.AlterField(
            model_name='cost_water',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='cost_water',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_machine_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_machine_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_temp1',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度設定1'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_temp2',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度設定2'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_temp3',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度設定3'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_temp4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度設定4'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_time',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運転時間'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_time1',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間1'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_time2',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間2'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_time3',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間3'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_recipe_time4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間4'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_history_input_date',
            field=models.DateField(verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_history_memo',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AlterField(
            model_name='solvent_conf',
            name='Solvent_unit_price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='solvent_manufacturer',
            name='Solvent_manu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='solvent_name',
            name='Solvent_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='溶剤名'),
        ),
        migrations.AlterField(
            model_name='unit_price_electric',
            name='Unit_price_electric',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='unit_price_gas',
            name='Unit_price_gas',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='unit_price_steam',
            name='Unit_price_steam',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='unit_price_water',
            name='Unit_price_water',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価'),
        ),
    ]
