# Generated by Django 3.2.8 on 2021-11-12 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=20)),
                ('machine_unit_no', models.IntegerField(blank=True, default=1)),
                ('machine_inst_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_couse_no', models.IntegerField(blank=True, null=True)),
                ('machine_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_data')),
            ],
        ),
        migrations.CreateModel(
            name='Machine_drive_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_drying_time', models.IntegerField(blank=True, default=0, null=True)),
                ('machine_drive_count', models.IntegerField(blank=True, default=0, null=True)),
                ('machine_drive_time_m', models.IntegerField(blank=True, default=0, null=True)),
                ('machine_drive_time_s', models.IntegerField(blank=True, default=0, null=True)),
                ('machine_steam_used', models.IntegerField(blank=True, default=0, null=True)),
                ('machine_electric_used', models.IntegerField(blank=True, default=0, null=True)),
                ('machime_air_used', models.IntegerField(blank=True, default=0, null=True)),
                ('machime_gas_used', models.IntegerField(blank=True, default=0, null=True)),
                ('data_date_month', models.IntegerField(blank=True, default=1, null=True)),
                ('data_date_day', models.IntegerField(blank=True, default=1, null=True)),
                ('data_datetime', models.DateTimeField(blank=True, null=True)),
                ('machine_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_setting')),
            ],
        ),
    ]
