# Generated by Django 3.2.8 on 2021-12-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvent_manufacturer',
            name='Solvent_name',
        ),
        migrations.AlterField(
            model_name='solvent_conf',
            name='Solvent_manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_manufacturer', verbose_name='メーカー'),
        ),
    ]
