# Generated by Django 3.2.8 on 2021-12-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble_history',
            name='Trouble_loss_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ロスタイム'),
        ),
    ]
