# Generated by Django 3.2.9 on 2022-01-01 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_name',
            name='Recipe_id',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種ID'),
        ),
        migrations.AlterField(
            model_name='setting_item',
            name='Setting_item_id',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種ID'),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Trouble_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='異常No'),
        ),
    ]
