# Generated by Django 3.2.9 on 2022-01-10 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solvent9_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent9', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent9_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent9_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent9_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent9_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent9_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent9_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤9設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent8_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent8', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent8_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent8_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent8_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent8_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent8_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent8_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤8設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent7_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent7', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent7_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent7_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent7_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent7_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent7_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent7_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤7設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent6_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent6', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent6_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent6_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent6_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent6_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent6_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent6_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤6設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent5_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent5', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent5_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent5_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent5_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent5_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent5_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent5_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤5設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent4_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent4', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent4_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent4_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent4_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent4_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent4_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent4_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤4設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent3_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent3', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent3_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent3_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent3_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent3_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent3_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent3_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤3設定',
            },
        ),
        migrations.CreateModel(
            name='Solvent2_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit_price_solvent2', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('Solvent2_input_date', models.DateField(blank=True, null=True, verbose_name='登録日')),
                ('Solvent2_memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('Solvent2_manu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent2_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー')),
                ('Solvent2_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent2_name', to='main_app.solvent_name', verbose_name='溶剤名')),
            ],
            options={
                'verbose_name_plural': '溶剤2設定',
            },
        ),
    ]
