# Generated by Django 3.2.9 on 2022-02-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouble_history',
            name='Customer_machine',
        ),
    ]
