# Generated by Django 3.2.9 on 2022-01-08 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_electric',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AddField(
            model_name='cost_electric',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Customer_machine_id',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Customer_recipe_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_electric_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_gas_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_steam_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Machine_water_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_electric',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_gas',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_solvent',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_steam',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_water',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水使用量'),
        ),
    ]
