# Generated by Django 3.2.9 on 2021-12-29 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_infomation',
            name='Customer_tel_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="半角数字 11桁で入力して下さい。 例:'09012345678'", regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
