# Generated by Django 3.2.9 on 2021-12-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_model',
            name='Machine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_category', to='main_app.equipment_category', verbose_name='装置カテゴリー'),
        ),
        migrations.AlterField(
            model_name='solvent_conf',
            name='Solvent_manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvent_manu', to='main_app.solvent_manufacturer', verbose_name='メーカー'),
        ),
    ]
