# Generated by Django 3.2.9 on 2022-01-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_electric',
            name='Machine_history_input_date',
            field=models.DateField(blank=True, null=True, verbose_name='登録日'),
        ),
    ]
