# Generated by Django 3.2.8 on 2021-11-12 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_data',
            name='data_date_year',
            field=models.IntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(2021)], verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='machine_inst_date',
            field=models.DateField(blank=True, null=True, verbose_name='納入日'),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='machine_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='装置名'),
        ),
        migrations.AlterField(
            model_name='machine_data',
            name='machine_unit_no',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='data_date_day',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='data_date_month',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='data_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='データ取得日'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machime_air_used',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='エア使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machime_gas_used',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_drive_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_drive_time_m',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運転時間:分'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_drive_time_s',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運転時間:秒'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_drying_time',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='乾燥時間'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_electric_used',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力使用量'),
        ),
        migrations.AlterField(
            model_name='machine_drive_data',
            name='machine_steam_used',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気使用量'),
        ),
        migrations.AlterField(
            model_name='machine_setting',
            name='set_couse_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='コースNo'),
        ),
    ]
