# Generated by Django 3.2.8 on 2022-02-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_maintenance_mail_setting_maintenance_machine_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_mail_setting',
            name='Maintenance_machine_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_log', verbose_name='稼働履歴'),
        ),
    ]
