# Generated by Django 3.2.9 on 2022-01-09 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220109_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_electric',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='cost_gas',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='cost_solvent',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='cost_steam',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='cost_total',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='cost_water',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='customer_machine_recipe',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AddField(
            model_name='trouble_history',
            name='Customer_machine_unit_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
    ]
