# Generated by Django 3.2.9 on 2021-12-29 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_infomation_customer_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_infomation',
            name='Customer_pastal_code',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="半角数字 7桁で入力して下さい。 例:'1234567'", regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='machine_model',
            name='Machine_model',
            field=models.CharField(max_length=20, unique=True, verbose_name='型式'),
        ),
    ]
