# Generated by Django 3.2.9 on 2021-12-25 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_machine',
            name='Customer_machine_id',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
    ]
