# Generated by Django 3.2.8 on 2021-12-31 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trouble_history_trouble_loss_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouble_history',
            name='Sig_plc_to_sys',
        ),
        migrations.RemoveField(
            model_name='trouble_history',
            name='Sig_sys_to_plc',
        ),
        migrations.AddField(
            model_name='trouble_history',
            name='Signal_plc_to_sys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trouble_history',
            name='Signal_sys_to_plc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Customer_machine_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='装置ID'),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Machine_model',
            field=models.CharField(max_length=20, verbose_name='型式'),
        ),
    ]
