# Generated by Django 3.2.9 on 2022-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220115_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_electric',
            name='Cost_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='コストID'),
        ),
    ]
