# Generated by Django 3.2.8 on 2021-11-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211123_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_electric',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_electric',
            name='Unit_price_electric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_electric', verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='cost_gas',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_gas',
            name='Unit_price_gas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_gas', verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='cost_solvent',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_solvent',
            name='Solvent_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_conf', verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='cost_steam',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_steam',
            name='Unit_price_steam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_steam', verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_electric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_electric', verbose_name='電力費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_gas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_gas', verbose_name='ガス費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_solvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_solvent', verbose_name='溶剤費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_steam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_steam', verbose_name='蒸気費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Cost_water',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cost_water', verbose_name='水費用'),
        ),
        migrations.AlterField(
            model_name='cost_total',
            name='Machine_drive_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_water',
            name='Machine_drive_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_drive_history', verbose_name='稼働履歴'),
        ),
        migrations.AlterField(
            model_name='cost_water',
            name='Unit_price_water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.unit_price_water', verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='customer_machine',
            name='Machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_model', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='customer_machine_recipe',
            name='Customer_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='machine_drive_history',
            name='Customer_machine_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine_recipe', verbose_name='品種'),
        ),
        migrations.AlterField(
            model_name='machine_model',
            name='Machine_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.equipment_category', verbose_name='装置カテゴリー'),
        ),
        migrations.AlterField(
            model_name='solvent_conf',
            name='Solvent_manu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_manufacturer', verbose_name='溶剤'),
        ),
        migrations.AlterField(
            model_name='solvent_manufacturer',
            name='Solvent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.solvent_name', verbose_name='溶剤'),
        ),
        migrations.AlterField(
            model_name='trouble_contents',
            name='Machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machine_model', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Customer_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer_machine', verbose_name='装置'),
        ),
        migrations.AlterField(
            model_name='trouble_history',
            name='Trouble_contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trouble_contents', verbose_name='異常'),
        ),
    ]
