# Generated by Django 3.2.9 on 2022-01-10 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220109_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_electric',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電力費用'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_gas',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ガス費用'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent0',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用0'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent1',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用1'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent2',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用2'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent3',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用3'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用4'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent5',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用5'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent6',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用6'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent7',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用7'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent8',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用8'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_solvent9',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤費用9'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_steam',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='蒸気費用'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_all',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_electric',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（電力）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_gas',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（ガス）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent0',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤0）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent1',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤1）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent2',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤2）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent3',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤3）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent4',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤4）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent5',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤5）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent6',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤6）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent7',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤7）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent8',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤8）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_solvent9',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（溶剤9）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_steam',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（蒸気）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_total_water',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='合計費用（水）'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Cost_water',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='水費用'),
        ),
        migrations.AlterField(
            model_name='cost_electric',
            name='Customer_machine_unit_no',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='号機'),
        ),
        migrations.AlterField(
            model_name='cost_electric',
            name='Customer_recipe_no',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='品種No'),
        ),
    ]
