# Generated by Django 3.2.8 on 2022-02-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_maintenance_mail_setting_maintenance_machine_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_count',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp0',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp1',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp10',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp11',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp2',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp3',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp4',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp5',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp6',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp7',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp8',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_temp9',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_time0',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_time1',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_time2',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_time3',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Machine_drive_time4',
        ),
    ]
