# Generated by Django 3.2.9 on 2022-01-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cost_electric_cost_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost_electric',
            name='Cost_id',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_day',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_hour',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_min',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_month',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_sec',
        ),
        migrations.RemoveField(
            model_name='machine_drive_history',
            name='Data_date_year',
        ),
    ]
