# Generated by Django 3.2.9 on 2022-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220102_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='型式'),
        ),
    ]
