# Generated by Django 3.2.9 on 2023-01-01 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220217_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count0',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数0'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count1',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数1'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count2',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数2'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count3',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数3'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count4',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数4'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count5',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数5'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count6',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数6'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count7',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数7'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count8',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数8'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_count9',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働回数9'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time0',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間0'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time1',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間1'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time2',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間2'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time3',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間3'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time4',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間4'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time5',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間5'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time6',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間6'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time7',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間7'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time8',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間8'),
        ),
        migrations.AlterField(
            model_name='machine_log',
            name='Machine_log_time9',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='稼働時間9'),
        ),
    ]
