# Generated by Django 3.2.9 on 2021-11-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211125_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost_electric',
            options={'verbose_name_plural': '電力コスト'},
        ),
        migrations.AlterModelOptions(
            name='cost_gas',
            options={'verbose_name_plural': 'ガスコスト'},
        ),
        migrations.AlterModelOptions(
            name='cost_solvent',
            options={'verbose_name_plural': '溶剤コスト'},
        ),
        migrations.AlterModelOptions(
            name='cost_steam',
            options={'verbose_name_plural': '蒸気コスト'},
        ),
        migrations.AlterModelOptions(
            name='cost_total',
            options={'verbose_name_plural': 'トータルコスト'},
        ),
        migrations.AlterModelOptions(
            name='cost_water',
            options={'verbose_name_plural': '水コスト'},
        ),
        migrations.AlterModelOptions(
            name='customer_infomation',
            options={'verbose_name_plural': '客先情報'},
        ),
        migrations.AlterModelOptions(
            name='customer_machine',
            options={'verbose_name_plural': '客先装置'},
        ),
        migrations.AlterModelOptions(
            name='customer_machine_recipe',
            options={'verbose_name_plural': 'レシピ情報'},
        ),
        migrations.AlterModelOptions(
            name='equipment_category',
            options={'verbose_name_plural': '装置カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='machine_drive_history',
            options={'verbose_name_plural': '稼働履歴'},
        ),
        migrations.AlterModelOptions(
            name='machine_model',
            options={'verbose_name_plural': '装置型式'},
        ),
        migrations.AlterModelOptions(
            name='solvent_conf',
            options={'verbose_name_plural': '溶剤設定'},
        ),
        migrations.AlterModelOptions(
            name='solvent_manufacturer',
            options={'verbose_name_plural': '溶剤メーカー'},
        ),
        migrations.AlterModelOptions(
            name='solvent_name',
            options={'verbose_name_plural': '溶剤名'},
        ),
        migrations.AlterModelOptions(
            name='trouble_contents',
            options={'verbose_name_plural': '異常内容'},
        ),
        migrations.AlterModelOptions(
            name='trouble_history',
            options={'verbose_name_plural': '異常履歴'},
        ),
        migrations.AlterModelOptions(
            name='unit_price_electric',
            options={'verbose_name_plural': '電力単価'},
        ),
        migrations.AlterModelOptions(
            name='unit_price_gas',
            options={'verbose_name_plural': 'ガス単価'},
        ),
        migrations.AlterModelOptions(
            name='unit_price_steam',
            options={'verbose_name_plural': '蒸気単価'},
        ),
        migrations.AlterModelOptions(
            name='unit_price_water',
            options={'verbose_name_plural': '水単価'},
        ),
    ]
