# Generated by Django 3.2.9 on 2022-01-03 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_machine_drive_history_machine_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_history',
            name='Data_date_hour',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='時'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Data_date_min',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='分'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Data_date_sec',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='秒'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_drive_temp10',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度10'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_drive_temp11',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='温度11'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_drive_time3',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運転時間3'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_drive_time4',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運転時間4'),
        ),
    ]
