# Generated by Django 3.2.9 on 2022-01-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220116_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_history',
            name='Customer_recipe_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='品種名'),
        ),
    ]
