# Generated by Django 3.2.9 on 2022-01-03 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220103_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent0_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤0使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent1_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤1使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent2_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤2使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent3_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤3使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent4_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤4使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent5_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤5使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent6_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤6使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent7_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤7使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent8_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤8使用量'),
        ),
        migrations.AddField(
            model_name='machine_drive_history',
            name='Machine_solvent9_used',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='溶剤9使用量'),
        ),
    ]
